front:
  enabled: true
  type: frontend
  name: r2devops-front
  image: registry.gitlab.com/r2devops/frontend
  tag: v0.83.7
  replicaCount: 1
  port: 80
  livenessEndpoint: "/"
  readinesspoint: "/"
  extraEnv: []
    # - name: xxx
    #   value: "yyyy"
  host: ""
  tls: {}
    # secretName: chart-example-tls
  resources: {}
    # limits:
    #   cpu: 200m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 64Mi

jobs:
  enabled: true
  type: backend
  name: r2devops-jobs
  image: registry.gitlab.com/r2devops/jobs
  tag: v1.3.3
  replicaCount: 1
  port: 3000
  livenessEndpoint: "/job/health/alive"
  readinesspoint: "/job/health/ready"
  extraEnv: []
  host: ""
  tls: {}
  resources: {}

worker:
  enabled: true
  type: backend
  name: r2devops-worker
  image: registry.gitlab.com/r2devops/jobs
  tag: v1.3.3
  replicaCount: 1
  command: ["./app"]
  args: ["--worker"]
  livenessEndpoint: "/job/health/alive"
  readinesspoint: "/job/health/ready"
  extraEnv: []
  host: ""
  tls: {}
  resources: {}

ingress:
  enabled: false
  className: ""
  annotations: {}

# ref. https://github.com/ory/k8s/blob/master/helm/charts/kratos/values.yaml
kratos:
  dependency:
    enabled: true

# ref. https://github.com/minio/minio/blob/master/helm/minio/values.yaml
minio:
  dependency:
    enabled: false
  custom:
    host: ""
    accessKey: ""
    secretKey: ""
  resources:
    requests:
      memory: 512Mi
  replicas: 1
  mode: standalone
  persistence:
    enabled: true
    size: 10Gi
  rootUser: admin
  rootPassword: pasWd8char

# ref. https://github.com/bitnami/charts/blob/main/bitnami/postgresql/values.yaml
postgresql:
  dependency:
    enabled: false
  custom:
    host: ""
    dbName: "r2devops"
  global:
    postgresql:
      auth:
        postgresPassword: secretpassword
  primary:
    initdb:
      scripts:
        # creates the database (ref. https://artifacthub.io/packages/helm/bitnami/postgresql#initialize-a-fresh-instance)
        init.sql: |
          CREATE DATABASE r2devops;

# ref. https://github.com/bitnami/charts/blob/main/bitnami/redis/values.yaml
redis:
  dependency:
    enabled: false
  custom:
    host: ""
  auth:
    password: secretpassword
  replica:
    replicaCount: 1
