stages:
  - lint
  - build
  - deploy

include:
  - remote: 'https://api.r2devops.io/job/r/gitlab/r2devops/hub/pages@0.5.1.yaml'

    #helm_lint:
    #  image: alpine:3.18
    #  stage: lint
    #  variables:
    #    CHART_PATH: "charts/r2devops"
    #  script:
    #    - apk add helm
    #    - helm lint $CHART_PATH

helm_package:
  image: alpine:3.18
  stage: build
  variables:
    CHART_PATH: "charts/r2devops"
    OUTPUT_PATH: "website_build"
  script:
    # Install helm cli
    - apk add helm
    # Create the artifact folder
    - mkdir $OUTPUT_PATH
    # Download all chart dependencies
    - helm dependency update $CHART_PATH
    # Package the chart
    - helm package $CHART_PATH -d $CHART_PATH/charts
    # Generate chart index file
    - helm repo index $CHART_PATH
    # Move everything to artifact folder
    - mv $CHART_PATH/charts $OUTPUT_PATH
  artifacts:
    paths:
      - $OUTPUT_PATH/

pages:
  rules:
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
