# Project information
site_name: R2Devops Self-hosted
site_description: 'An online documentation to know how to configure R2Devops for a self-hosted instance'
site_author: 'Arsène Fougerouse<arsene@r2devops.io>'
site_url: 'http://selhosted.r2devops.io'

# Copyright
copyright: 'Copyright © R2Devops'

# Repository
repo_name: 'self-hosted'
repo_url: 'https://gitlab.com/r2devops/self-hosted'

# Navigation
nav:
  - Documentation:
    - Getting Started: index.md
    - Requirements: requirements.md
    - Configuration: 
      - Application: configuration-app.md
      - Domain name: configuration-domain.md
      - GitLab OIDC: configuration-oidc.md
      - SMTP Server: configuration-smtp.md
      - Checks: configuration-check.md
    - Customization: customization.md
    - Troubleshooting: troubleshooting.md



# Customization
extra:
  social:
    - icon: 'fontawesome/solid/globe'
      link: 'https://www.r2devops.io/'
    - icon: 'fontawesome/brands/gitlab'
      link: 'https://gitlab.com/r2devops/self-hosted'
    - icon: 'fontawesome/solid/envelope'
      link: 'mailto:thomas@r2devops.io'
extra_css:
    - css/extra.css

# Configuration
theme:
  name: 'material'
  # Color
  palette:
    primary: 'light blue' # Choose: https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
    accent: 'light blue'
  # Text
  language: 'en'
  direction: 'ltr'
  font:
    text: 'Roboto'
    code: 'Roboto mono'
  # Images
  favicon: 'images/self-hosted.png'
  logo: 'images/self-hosted.png'

# Extensions (https://squidfunk.github.io/mkdocs-material/extensions/admonition/)
markdown_extensions:
  - attr_list
  - admonition # block-styled content (note, idea, warning, ...)
  - codehilite # highlite code syntax
  - footnotes # references in footnotes
  - toc:
      permalink: true # anchor on titles
  # PyMdown extensions (https://squidfunk.github.io/mkdocs-material/extensions/pymdown)
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      # emoji_generator: !!python/name:pymdownx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.tabbed
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.tilde

# Plugins (https://squidfunk.github.io/mkdocs-material/plugins/minify-html/)
plugins:
  - search # search input
  - git-revision-date-localized # revision date at the end of pages
  - minify:
      minify_html: true # minification of html
