---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ .Values.front.name }}
    app.kubernetes.io/name: {{ .Values.front.name }}
  name: {{ .Values.front.name }}
data:
  config.json: |
    {
      "appTitle": "R2Devops",
      "apiUrl": "https://{{ .Values.jobs.host }}",
      "apiUrlIdentities": "https://{{ .Values.jobs.host }}/kratos/public",
      "gitLabApiUrl": "{{ (index .Values.kratos.kratos.config.selfservice.methods.oidc.config.providers 0).issuer_url }}",
      "selfHosted": true,
      "docUrl": "https://docs.r2devops.io"
    }
